### ISSUE TITLE
A question about pyrchain

### ISSUE THREAD

**Issue by HiXiaozhe** [zsluedem/zsluedem#1]
Hello WillQ, I am a computer oriented undergraduate student who is currently researching and learning about Rchain's blockchain project. I have encountered some problems while using pyrchain, an interface(https://github.com/rchain/pyrchain) written with your participation, and would like to get your guidance.
QUESTION: Once I have deployed the smart contract and proposed it, how will I get the messages in the channel and present them.
Looking forward to your answer, thank you very much!

**Comment by zsluedem** [comment]
@HiXiaozhe Hm.. What kind of code do you deploy? You could use explore_deploy to get the message in the channel. Somthing like this https://github.com/rchain/pyrchain/blob/master/rchain/vault.py

**Comment by HiXiaozhe** [comment]
For example, a smart contract like this
”“”
new result in {
    result!("Hello World!")
}
“”“
I used this method 'send_deploy()' and 'propose()' from rchain.RClient.
How do I get the message "Hello World!" from the channel?
I tried the 'get_data_at_public_names()' method, but it doesn't work!

**Comment by zsluedem** [comment]
I don't remember, actually. Why are you still playing some dead codes? I remember there is a preview name function which you could preview the name `result` in your deploy and you could use that to get the message in the channel.

**Comment by HiXiaozhe** [comment]
Thanks for your help, I will make some attempts to follow what you said.

**Comment by zsluedem** [comment]
Close it if you don't have any questions.
